//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _LINUXCOMMUNICATIONSPROGRAM_CLIENT_WXCRAFTER_BASE_CLASSES_H
#define _LINUXCOMMUNICATIONSPROGRAM_CLIENT_WXCRAFTER_BASE_CLASSES_H

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/textctrl.h>
#include <wx/button.h>
#include <wx/listbox.h>
#include <wx/statbox.h>
#include <wx/filepicker.h>
#include <wx/gauge.h>
#include <wx/stattext.h>
#include <wx/menu.h>
#include <wx/toolbar.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class MainFrameBaseClass : public wxFrame
{
protected:
	wxTextCtrl* Connection_TextBox;
	wxButton* Connection_Button;
	wxTextCtrl* Message_Input;
	wxButton* Send_Msg;
	wxListBox* ListBox;
	wxListBox* User_List;
	wxButton* Voice_Button;
	wxButton* Video_Button;
	wxButton* Send_File;
	wxFilePickerCtrl* Pick_File;
	wxGauge* MyFileGauge;
	wxStaticText* AStream_Text;
	wxStaticText* AStream_Percentage;
	wxButton* AStream_Yes;
	wxButton* AStream_No;
	wxStaticText* BStream_Text;
	wxStaticText* BStream_Percentage;
	wxButton* BStream_Yes;
	wxButton* BStream_No;
	wxStaticText* CStream_Text;
	wxStaticText* CStream_Percentage;
	wxButton* CStream_Yes;
	wxButton* CStream_No;
	wxMenuBar* m_menuBar;
	wxMenu* m_name6;
	wxMenuItem* m_menuItem7;
	wxToolBar* m_mainToolbar;

protected:
	virtual void ChatEnter(wxCommandEvent& event)
	{
		event.Skip();
	}
	virtual void UserList_Select(wxCommandEvent& event)
	{
		event.Skip();
	}
	virtual void FileMenuOpen(wxMenuEvent& event)
	{
		event.Skip();
	}
	virtual void OnMenuitem7MenuSelected(wxCommandEvent& event)
	{
		event.Skip();
	}

public:
	wxTextCtrl* GetConnection_TextBox()
	{
		return Connection_TextBox;
	}
	wxButton* GetConnection_Button()
	{
		return Connection_Button;
	}
	wxTextCtrl* GetMessage_Input()
	{
		return Message_Input;
	}
	wxButton* GetSend_Msg()
	{
		return Send_Msg;
	}
	wxListBox* GetListBox()
	{
		return ListBox;
	}
	wxListBox* GetUser_List()
	{
		return User_List;
	}
	wxButton* GetVoice_Button()
	{
		return Voice_Button;
	}
	wxButton* GetVideo_Button()
	{
		return Video_Button;
	}
	wxButton* GetSend_File()
	{
		return Send_File;
	}
	wxFilePickerCtrl* GetPick_File()
	{
		return Pick_File;
	}
	wxGauge* GetMyFileGauge()
	{
		return MyFileGauge;
	}
	wxStaticText* GetAStream_Text()
	{
		return AStream_Text;
	}
	wxStaticText* GetAStream_Percentage()
	{
		return AStream_Percentage;
	}
	wxButton* GetAStream_Yes()
	{
		return AStream_Yes;
	}
	wxButton* GetAStream_No()
	{
		return AStream_No;
	}
	wxStaticText* GetBStream_Text()
	{
		return BStream_Text;
	}
	wxStaticText* GetBStream_Percentage()
	{
		return BStream_Percentage;
	}
	wxButton* GetBStream_Yes()
	{
		return BStream_Yes;
	}
	wxButton* GetBStream_No()
	{
		return BStream_No;
	}
	wxStaticText* GetCStream_Text()
	{
		return CStream_Text;
	}
	wxStaticText* GetCStream_Percentage()
	{
		return CStream_Percentage;
	}
	wxButton* GetCStream_Yes()
	{
		return CStream_Yes;
	}
	wxButton* GetCStream_No()
	{
		return CStream_No;
	}
	wxMenuBar* GetMenuBar()
	{
		return m_menuBar;
	}
	wxToolBar* GetMainToolbar()
	{
		return m_mainToolbar;
	}
	MainFrameBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Linux Communications System"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,650), long style = wxDEFAULT_FRAME_STYLE|wxFRAME_TOOL_WINDOW|wxSYSTEM_MENU|wxFULL_REPAINT_ON_RESIZE|wxBORDER_NONE|wxBORDER_STATIC);
	virtual ~MainFrameBaseClass();
};

#endif
